// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovePara.Model;

#nullable disable

namespace MovePara.Migrations
{
    [DbContext(typeof(ParaDbContext))]
    [Migration("20220118023526_StoredProc")]
    partial class StoredProc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovePara.Model.Para", b =>
                {
                    b.Property<int>("ParaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParaId"), 1L, 1);

                    b.Property<string>("ParaText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParaId");

                    b.ToTable("para");

                    b.HasData(
                        new
                        {
                            ParaId = 1,
                            ParaText = "A"
                        },
                        new
                        {
                            ParaId = 2,
                            ParaText = "B"
                        },
                        new
                        {
                            ParaId = 3,
                            ParaText = "C"
                        },
                        new
                        {
                            ParaId = 4,
                            ParaText = "D"
                        });
                });

            modelBuilder.Entity("MovePara.Model.ParaLeft", b =>
                {
                    b.Property<int>("ParaId")
                        .HasColumnType("int");

                    b.HasIndex("ParaId");

                    b.ToTable("paraLeft");
                });

            modelBuilder.Entity("MovePara.Model.ParaRight", b =>
                {
                    b.Property<int>("ParaId")
                        .HasColumnType("int");

                    b.HasIndex("ParaId");

                    b.ToTable("paraRight");
                });

            modelBuilder.Entity("MovePara.Model.ParaLeft", b =>
                {
                    b.HasOne("MovePara.Model.Para", "Para")
                        .WithMany()
                        .HasForeignKey("ParaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Para");
                });

            modelBuilder.Entity("MovePara.Model.ParaRight", b =>
                {
                    b.HasOne("MovePara.Model.Para", "Para")
                        .WithMany()
                        .HasForeignKey("ParaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Para");
                });
#pragma warning restore 612, 618
        }
    }
}
