// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovePara.Model;

#nullable disable

namespace MovePara.Migrations
{
    [DbContext(typeof(ParaDbContext))]
    partial class ParaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovePara.Model.Para", b =>
                {
                    b.Property<string>("ParaId")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(2);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ParaText")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.HasKey("ParaId");

                    b.ToTable("para");

                    b.HasData(
                        new
                        {
                            ParaId = "A",
                            Id = 0,
                            ParaText = "This is Para A"
                        },
                        new
                        {
                            ParaId = "B",
                            Id = 0,
                            ParaText = "This is Para B"
                        },
                        new
                        {
                            ParaId = "C",
                            Id = 0,
                            ParaText = "This is Para C"
                        },
                        new
                        {
                            ParaId = "D",
                            Id = 0,
                            ParaText = "This is Para D"
                        });
                });

            modelBuilder.Entity("MovePara.Model.ParaLeft", b =>
                {
                    b.Property<string>("ParaId")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(2);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("ParaId");

                    b.ToTable("paraLeft");
                });

            modelBuilder.Entity("MovePara.Model.ParaRight", b =>
                {
                    b.Property<string>("ParaId")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(2);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("ParaId");

                    b.ToTable("paraRight");
                });

            modelBuilder.Entity("MovePara.Model.ParaLeft", b =>
                {
                    b.HasOne("MovePara.Model.Para", "Para")
                        .WithMany()
                        .HasForeignKey("ParaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Para");
                });

            modelBuilder.Entity("MovePara.Model.ParaRight", b =>
                {
                    b.HasOne("MovePara.Model.Para", "Para")
                        .WithMany()
                        .HasForeignKey("ParaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Para");
                });
#pragma warning restore 612, 618
        }
    }
}
